### ISSUE TITLE
BottomBarView Icon Not active for detail view

### ISSUE THREAD

**Issue by vaishnavi2122** [furkanaskin/TrickyNavigationSample#4]
Hi thank you very much for useful app. 

When moving from Search -> Dynamic Title Fragment and then directly to Home tab. Backstack is maintained properly but when showing Dynamic Title Fragment from backstack "Search" tab not getting highlighted.

**Comment by furkanaskin** [comment]
So, what’s wrong in here? You can see same behaviour in other applications. Dynamic toolbar screen didn’t attached to any tab item. It just a fragment and in your scenario : Search -> Dynamic Toolbar -> Games -> Dynamic Toolbar(with backpress)
NavController just knows search page is an tab item and also the game page. Because of this it didn’t highlights the Search page when the current is Dynamic Toolbar.
For making this possible, in my opinion you can use bottomNavigationView.setSelectedItemId(id : Int) in Dynamic Toolbar screen.
